version: '3.4'

services:
   my-redis:
      container_name: my-redis
      restart: always
      ports:
          - "6379:6379"
      volumes:
        - postgres_my-redis:/var/lib/postgresql/data/


   jewelryec-backend:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
      ports:
        - "8080"
        - "8081"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
